import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Header from "@/components/ui/header";
import { Toaster } from "@/components/ui/toaster";
import { LoginProvider } from "@/utils/useLogin";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RoadEye",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <LoginProvider>
      <html lang='en'>
        <body className={inter.className}>
          {children}
          <Toaster />
        </body>
      </html>
    </LoginProvider>
  );
}
